Paginate = 6
assetDir = "assets/"
baseurl = "/"
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
paginatePath = "page"
publishdir = "public"
title = "NSP"


[Params]
author = "NSP"
description = "NSP"
favicon = "img/svg/icon.svg"
logo = "img/logo.png"
rss = true
url = "/"
[[menu.main]]
name = "Про NSP"
url = "#"
weight = 1
identifier = "NSP"
[[menu.main]]
name = "Якість продукції"
url = "#"
weight = 1
parent = "NSP"
[[menu.main]]
name = "Наука та лабораторія"
url = "#"
weight = 2
parent = "NSP"
[[menu.main]]
name = "Реєстрація та сертифікація"
url = "#"
weight = 3
parent = "NSP"
[[menu.main]]
name = "Порівняння з конкурентами"
url = "#"
weight = 4
parent = "NSP"
[[menu.main]]
name = "Прайс-лист КАТАЛОГ"
url = "#"
weight = 2
[[menu.main]]
name = "Доставка"
url = "#"
weight = 3
[[menu.main]]
name = "Покупцям"
url = "#"
weight = 4
identifier = "by"
[[menu.main]]
name = "Компьютерна діагностика"
url = "/computer-diagnostics/"
weight = 1
parent = "by"
[[menu.main]]
name = "Схеми застосування"
url = "#"
weight = 2
parent = "by"
[[menu.main]]
name = "Новини"
url = "#"
weight = 3
parent = "by"
[[menu.main]]
name = "Статті"
url = "/article/"
weight = 4
parent = "by"
[[menu.main]]
name = "Система бонусів"
url = "/bonus/"
weight = 5
parent = "by"
[[menu.main]]
name = "Контакти"
url = "/contact"
weight = 6
parent = "by"

 


DefaultContentLanguage = "en"
blog = "/blog/:year/:month/:day/:slug"
metaDataFormat = "md"
post = "/blog/:year/:month/:slug/"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
